import Head from "next/head";
import { Inter } from "@next/font/google";
import { Hero } from "@/components/Hero";
import { Layout } from "@/components/Layout";
import { Banner } from "@/components/Banner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Linear App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <Banner />
      </Layout>
    </>
  );
}
